### ISSUE TITLE
Plugin by name 'Recaptcha' was not found in the registry

### ISSUE THREAD

**Issue by Nadermane** [dachcom-digital/pimcore-formbuilder#43]
Heya, I'm having some issues getting the recaptchas to work in formbuilder. It seems that I am missing some plugin for it to work properly. I could use some advice on how to fix it.

```
Plugin by name 'Recaptcha' was not found in the registry; used paths:
Twitter_Bootstrap3_Form_Element_:
Twitter/Bootstrap3/Form/Element/ Cgsmith\Form\Element\:
/Cgsmith/Form/Element/ Formbuilder\Zend\Form\Element\Html5Text\:
/home/[redacted]/plugins/Formbuilder/lib/Formbuilder/Zend/Form/Element/Html5Text/ Formbuilder\Zend\Form\Element\:
/home/[redacted]/plugins/Formbuilder/lib/Formbuilder/Zend/Form/Element/ Zend_Form_Element_:
Zend/Form/Element/

#0 /home/[redacted]/vendor/zendframework/zendframework1/library/Zend/Form.php(1133): Zend_Loader_PluginLoader->load('recaptcha')
#1 /home/[redacted]/plugins/Formbuilder/lib/Twitter/Bootstrap3/Form.php(369): Zend_Form->createElement('recaptcha', 'captcha', Array)
#2 /home/[redacted]/plugins/Formbuilder/lib/Formbuilder/Zend/Traits/Form.php(241): Twitter_Bootstrap3_Form->createElement('recaptcha', 'captcha', Array)
```

**Comment by solverat** [comment]
strange... i just checked it and i had no problems doing so. you need to install formbuilder with composer because of the classmap generation. you also could try the [dump autload](https://getcomposer.org/doc/03-cli.md#dump-autoload) command.
